apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
- name: cn.harmonycloud.admission-registry
  rules:
  - apiGroups:   ["apps",""]
    apiVersions: ["v1"]
    operations:  ["CREATE","UPDATE"]
    resources:   ["deployments"]
  clientConfig:
    service:
      namespace: default
      name: admission-registry
      path: "/admission/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lKQUt1Sy9Kd0RLL3dpTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ2t4SnpBbEJnTlYKQkFNTUhtRmtiV2x6YzJsdmJpMXlaV2RwYzNSeWVTNWtaV1poZFd4MExuTjJZekFlRncweU1qQTNNamd3TWpRegpNRGxhRncwek1qQTNNalV3TWpRek1EbGFNQ2t4SnpBbEJnTlZCQU1NSG1Ga2JXbHpjMmx2YmkxeVpXZHBjM1J5CmVTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbUoKeklrRElBWTkwSVBpSVlzSGZDSWVIb3RTeEVRcnliSHRZMFpCNE5vUURQdk5NSzZDeU5KaHUza0xxSTVtTHhheApCYnovU2NuQnVtcVg2d1BMdXRSNVJyUENQNkVEN2VrU05vV3B3SmhLSlRPblMxOVZZdTk5UlkwSGNkMGg0T09UCis0dlZCWmhMcmVOVmQ3QkNKYWdzQjQ2dGE1U1R3ekxacXM3RzVpbGR1Sy84eWUzU3VyeFJXcmNhSmJKREh0WGEKbFZyUXJ0eGkrdmNISTFMbm91R1Q0a2Z4UW84VzlpTVByYzM4dmxJeVBNaWFjNFE3R3BBT1BSWEJNS2ZUcDRlMwoxY0lZeCtvS2ZuaHB3MEpncndPMExiQ016V1NyeDJNM3NXdFNPUG9jSDFmTlZyOTBYWHpjS2hTQVl4ZFdjY1Q3ClJuM1dCS0hyVXBwSS9zbWJBUXNDQXdFQUFhTlFNRTR3SFFZRFZSME9CQllFRkVpaVV2cEJkYjVQd1ZJdFRuMUoKMk92THE0MXVNQjhHQTFVZEl3UVlNQmFBRkVpaVV2cEJkYjVQd1ZJdFRuMUoyT3ZMcTQxdU1Bd0dBMVVkRXdRRgpNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEbkNDTFZvdUEwUldCK3h0SVdwMzdjNUJCeThjWHZFCjBVYWM0RnpmVlNoK1RNRXByQXB6dXMwc3NHNEg4ZllvNTNOL3BLd1cxV05hVDZEMytFN3poQmxaSUM0RmU0UUoKVzFRZHdmZ00yRTNZTTVBdzdWeFU3YnVUZ1ppQTBJQ0p0T21ZKzZDQVQwQzhuWFZIblA4aUZXdmhsNmIzYlQrRQpZcFBRTEg3ODc3cUx3MTZabk95emp4VVg2dkNxbytDcjhncU9EaFNGVVA4SmxCNDF5VGQ3VC83Y0lGOVBLRlU4CjJvZXJWK2o5UWU1SnQweUtXMTRNUFh3VjJCY05QcWpOdFB2Z05WNkhoWHNjR0VteHRvL21oWTRPcHdESmV4RnkKM3Rkcm1iT3EwSWxPaEpNZDRhMjB4WlNEaW9VWmc4UEdUOGZqV2U0ZmFLRnJXRGNMUXliSldWUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
  # namespaceSelector:
  #   matchLabels:
  #     admission-webhook: enabled